version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: barbearia-back-end
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_DATABASE: barbearia-database
    ports:
      - "3356:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge