spring.application.name=back-end

# Configurações do banco de dados
# DICA: Verifique se a porta 3356 está correta para o seu MySQL
spring.datasource.url=jdbc:mysql://localhost:3356/barbearia-database?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Jackson (Ajustado para evitar o erro de Enum)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.default-property-inclusion=non_null

# Pool de Conexões (Hikari)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=alpha