# Servidor
server.port=8080
server.servlet.context-path=/api
server.servlet.encoding.charset=UTF-8

# Base de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3356/barbearia_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT
jwt.secret=god_of_war_platinado_2023_por_eu
jwt.expiration=86400000
jwt.issuer=api-projeto-barbearia

# Logging
logging.level.root=WARN
logging.level.com.inicio.back_end=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null

# Validação
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false